Port 22
ListenAddress 0.0.0.0
PermitRootLogin yes
PasswordAuthentication yes
AllowTcpForwarding no
PidFile /run/sshd_target.pid
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
UsePAM no
StrictModes no
PrintMotd no
